ALTER TABLE Benevole 
ADD CONSTRAINT appartient 
FOREIGN KEY(NumEquipe) REFERENCES Equipe(IdEquipe) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE Benevole
ADD CONSTRAINT souhaite
FOREIGN KEY(IdBenevole) REFERENCES Preference(IdBenevole) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE Benevole
ADD CONSTRAINT participe
FOREIGN KEY(IdEquipeCovoit) REFERENCES EquipeCovoit(IdEquipeCovoit) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE Responsable
ADD CONSTRAINT gère
FOREIGN KEY(IdResponsable) REFERENCES Benevole(IdBenevole) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE Materiel
ADD CONSTRAINT possède
FOREIGN KEY(IdResponsable) REFERENCES Responsable(IdResponsable) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE Equipe
ADD CONSTRAINT geree
FOREIGN KEY(IdResponsable) REFERENCES Responsable(IdResponsable) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE Equipe
ADD CONSTRAINT est
FOREIGN KEY(CoorLieu) REFERENCES Lieu(CoorLieu) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE CreneauHoraire
ADD CONSTRAINT concerne
FOREIGN KEY(IdEquipe) REFERENCES Equipe(IdEquipe) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE CreneauHoraire
ADD CONSTRAINT situe
FOREIGN KEY(CoorLieu) REFERENCES Lieu(CoorLieu) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE Voiture
ADD CONSTRAINT conduit
FOREIGN KEY(IdBenevole) REFERENCES Benevole(IdBenevole) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE Voiture
ADD CONSTRAINT voyage
FOREIGN KEY(IdEquipeCovoit) REFERENCES EquipeCovoit(IdEquipeCovoit) ON DELETE CASCADE ON UPDATE CASCADE;



