ALTER TABLE Benevole 
ADD CONSTRAINT appartient
FOREIGN KEY(NumEquipe) REFERENCES equipe(IdEquipe) ON DELETE CASCADE ON UPDATE CASCADE;


ALTER TABLE CreneauHoraire
ADD CONSTRAINT concerne
FOREIGN KEY(IdEquipe) REFERENCES equipe(IdEquipe) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE CreneauHoraire
ADD CONSTRAINT situe
FOREIGN KEY(CoorLieu) REFERENCES lieu(CoorLieu) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE Voiture
ADD CONSTRAINT conduit
FOREIGN KEY(IdBenevole) REFERENCES benevole(IdBenevole) ON DELETE CASCADE ON UPDATE CASCADE;




