INSERT INTO Lieu VALUES (0, PZ, Gestion du parking)
INSERT INTO Lieu VALUES (6, PD, Gestion du parking)
INSERT INTO Lieu VALUES (12, PE, Gestion du parking)
INSERT INTO Lieu VALUES (18, PT, Gestion du parking)
INSERT INTO Lieu VALUES (24, PQ, Gestion du parking)
INSERT INTO Lieu VALUES (30, PS, Gestion du parking)
INSERT INTO Lieu VALUES (36, PP, Gestion du parking)
INSERT INTO Lieu VALUES (42, RR, Redirection vers le meeting pour public et VIP)
INSERT INTO Lieu VALUES (48, RG, Redirection vers le meeting pour public)
INSERT INTO Lieu VALUES (54, LB, Contrôle des billets VIP)
INSERT INTO Lieu VALUES (60, IA, )
INSERT INTO Lieu VALUES (64, IB, )
INSERT INTO Lieu VALUES (68, IC, )
INSERT INTO Lieu VALUES (72, ID, )
INSERT INTO Lieu VALUES (76, IE, )
INSERT INTO Lieu VALUES (80, IF, )INSERT INTO Lieu VALUES (0, PZ, Gestion du parking)
INSERT INTO Lieu VALUES (6, PD, Gestion du parking)
INSERT INTO Lieu VALUES (12, PE, Gestion du parking)
INSERT INTO Lieu VALUES (18, PT, Gestion du parking)
INSERT INTO Lieu VALUES (24, PQ, Gestion du parking)
INSERT INTO Lieu VALUES (30, PS, Gestion du parking)
INSERT INTO Lieu VALUES (36, PP, Gestion du parking)
INSERT INTO Lieu VALUES (42, RR, Redirection vers le meeting pour public et VIP)
INSERT INTO Lieu VALUES (48, RG, Redirection vers le meeting pour public)
INSERT INTO Lieu VALUES (54, LB, Contrôle des billets VIP)
INSERT INTO Lieu VALUES (60, IA, )
INSERT INTO Lieu VALUES (64, IB, )
INSERT INTO Lieu VALUES (68, IC, )
INSERT INTO Lieu VALUES (72, ID, )
INSERT INTO Lieu VALUES (76, IE, )
INSERT INTO Lieu VALUES (80, IF, )
INSERT INTO Lieu VALUES (0, PZ, Gestion du parking)
INSERT INTO Lieu VALUES (6, PD, Gestion du parking)
INSERT INTO Lieu VALUES (12, PE, Gestion du parking)
INSERT INTO Lieu VALUES (18, PT, Gestion du parking)
INSERT INTO Lieu VALUES (24, PQ, Gestion du parking)
INSERT INTO Lieu VALUES (30, PS, Gestion du parking)
INSERT INTO Lieu VALUES (36, PP, Gestion du parking)
INSERT INTO Lieu VALUES (42, RR, Redirection vers le meeting pour public et VIP)
INSERT INTO Lieu VALUES (48, RG, Redirection vers le meeting pour public)
INSERT INTO Lieu VALUES (54, LB, Contrôle des billets VIP)
INSERT INTO Lieu VALUES (60, IA, )
INSERT INTO Lieu VALUES (64, IB, )
INSERT INTO Lieu VALUES (68, IC, )
INSERT INTO Lieu VALUES (72, ID, )
INSERT INTO Lieu VALUES (76, IE, )
INSERT INTO Lieu VALUES (80, IF, )
INSERT INTO Lieu VALUES (0, PZ, Gestion du parking)
INSERT INTO Lieu VALUES (6, PD, Gestion du parking)
INSERT INTO Lieu VALUES (12, PE, Gestion du parking)
INSERT INTO Lieu VALUES (18, PT, Gestion du parking)
INSERT INTO Lieu VALUES (24, PQ, Gestion du parking)
INSERT INTO Lieu VALUES (30, PS, Gestion du parking)
INSERT INTO Lieu VALUES (36, PP, Gestion du parking)
INSERT INTO Lieu VALUES (42, RR, Redirection vers le meeting pour public et VIP)
INSERT INTO Lieu VALUES (48, RG, Redirection vers le meeting pour public)
INSERT INTO Lieu VALUES (54, LB, Contrôle des billets VIP)
INSERT INTO Lieu VALUES (60, IA, )
INSERT INTO Lieu VALUES (64, IB, )
INSERT INTO Lieu VALUES (68, IC, )
INSERT INTO Lieu VALUES (72, ID, )
INSERT INTO Lieu VALUES (76, IE, )
INSERT INTO Lieu VALUES (80, IF, )
INSERT INTO Lieu VALUES (0, PZ, Gestion du parking)
INSERT INTO Lieu VALUES (6, PD, Gestion du parking)
INSERT INTO Lieu VALUES (12, PE, Gestion du parking)
INSERT INTO Lieu VALUES (18, PT, Gestion du parking)
INSERT INTO Lieu VALUES (24, PQ, Gestion du parking)
INSERT INTO Lieu VALUES (30, PS, Gestion du parking)
INSERT INTO Lieu VALUES (36, PP, Gestion du parking)
INSERT INTO Lieu VALUES (42, RR, Redirection vers le meeting pour public et VIP)
INSERT INTO Lieu VALUES (48, RG, Redirection vers le meeting pour public)
INSERT INTO Lieu VALUES (54, LB, Contrôle des billets VIP)
INSERT INTO Lieu VALUES (60, IA, )
INSERT INTO Lieu VALUES (64, IB, )
INSERT INTO Lieu VALUES (68, IC, )
INSERT INTO Lieu VALUES (72, ID, )
INSERT INTO Lieu VALUES (76, IE, )
INSERT INTO Lieu VALUES (80, IF, )
INSERT INTO Lieu VALUES (0, PZ, Gestion du parking)
INSERT INTO Lieu VALUES (6, PD, Gestion du parking)
INSERT INTO Lieu VALUES (12, PE, Gestion du parking)
INSERT INTO Lieu VALUES (18, PT, Gestion du parking)
INSERT INTO Lieu VALUES (24, PQ, Gestion du parking)
INSERT INTO Lieu VALUES (30, PS, Gestion du parking)
INSERT INTO Lieu VALUES (36, PP, Gestion du parking)
INSERT INTO Lieu VALUES (42, RR, Redirection vers le meeting pour public et VIP)
INSERT INTO Lieu VALUES (48, RG, Redirection vers le meeting pour public)
INSERT INTO Lieu VALUES (54, LB, Contrôle des billets VIP)
INSERT INTO Lieu VALUES (60, IA, )
INSERT INTO Lieu VALUES (64, IB, )
INSERT INTO Lieu VALUES (68, IC, )
INSERT INTO Lieu VALUES (72, ID, )
INSERT INTO Lieu VALUES (76, IE, )
INSERT INTO Lieu VALUES (80, IF, )
