INSERT INTO Lieu (CoorLieu, Nom, Tache) VALUES
("HB", "Baptème Helicopteres", "Encadrer les visiteurs pour les baptemes"),
("NB", "Zone Entree", "Accueil et surveillance des barrieres"),
("NE", "Zone Entree", "Accueil et surveillance des barrieres"),
("ND", "Zone Entree", "Surveillance des barrieres"),
("NA", "Zone Entree", "Accueil et information des objets interdits"),
("NC", "Zone Entree", "Surveillance des barrieres pres de la piste ULM"),
("SC", "Zone Exposants", "Surveillance des barrieres pres de la piste ULM"),
("SD", "Zone Exposants", "Surveillance de la zone publique"),
("SB", "Zone Exposants", "Surveillance de la zone publique"),
("SF", "Zone Exposants", "Surveillance de la zone publique et des toilettes"),
("SE", "Zone Exposants", "Surveillance de la zone publique"),
("IB", "Zone bord de piste", "Surveillance des barrieres"),
("IC", "Zone bord de piste", "Surveillance des barrieres"),
("IA", "Zone bord de piste", "Surveillance des barrieres"),
("ID", "Zone bord de piste", "Surveillance des barrieres"),
("ZT", "Zone Trescal", "Surveillance des barrieres et de la zone Trescal"),
("AA", "Zone Amis d'Airexpo", "Surveillance des barrieres et de la zone Amis d'Airexpo"),
("IE", "Zone bord de piste", "Surveillance des barrieres"),
("SG", "Zone Exposants", "Surveillance de la zone publique et des hangars ULM"),
("IF", "Zone bord de piste", "Surveillance des barrieres"),
("ZV", "Zone VIP", "Surveillance des barrieres et de la zone VIP"),
("SA", "Zone publique", "Redirection du public et accueil"),
("EV", "Entree VIP", "Controle de l'entrée VIP");