INSERT INTO Lieu (CoorLieu, Nom, Tache) VALUES
("PZ", "Parking P0 (1200 places)", "Gestion du parking"),
("PD", "Parking P2 (1200 places)", "Gestion du parking"),
("PE", "Parking P2+ (1800 places ?)", "Gestion du parking"),
("PT", "Parking P3 (1800 places)", "Gestion du parking"),
("PQ", "Parking P5 (200 places)", "Gestion du parking"),
("PS", "Parking P6 (1600 places)", "Gestion du parking"),
("PP", "Parking P7 (600 places)", "Gestion du parking"),
("RR", "Rd-pt Muret", "Redirection vers le meeting pour public et VIP"),
("RG", "Rd-pt sud Muret ", "Redirection vers le meeting pour public"),
("LB", "Labastidette", "Contrôle des billets VIP"),
("IA", "", ""),
("IB", "", ""),
("IC", "", ""),
("ID", "", ""),
("IE", "", ""),
("IF", "", "");
